name: deploy docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - run: |
          pip install mkdocs-material
          pip install mkdocs-static-i18n[material]
          pip install mkdocs-render-swagger-plugin

      - run: mkdocs gh-deploy --config-file ./docs/mkdocs.yml